import { type Currency } from '../types/index';

export const CURRENCIES: Currency[] = [
  { code: 'XAU_G', name: 'Gold (gram)', countryCode: 'xx', isMetal: true },
  { code: 'XAU_T', name: 'Gold (troy ounce)', countryCode: 'xx', isMetal: true },
  { code: 'USD', name: 'United States Dollar', countryCode: 'us' },
  { code: 'EUR', name: 'Euro', countryCode: 'eu' },
  { code: 'JPY', name: 'Japanese Yen', countryCode: 'jp' },
  { code: 'GBP', name: 'British Pound Sterling', countryCode: 'gb' },
  { code: 'AUD', name: 'Australian Dollar', countryCode: 'au' },
  { code: 'CAD', name: 'Canadian Dollar', countryCode: 'ca' },
  { code: 'CHF', name: 'Swiss Franc', countryCode: 'ch' },
  { code: 'CNY', name: 'Chinese Yuan', countryCode: 'cn' },
  { code: 'HKD', name: 'Hong Kong Dollar', countryCode: 'hk' },
  { code: 'TWD', name: 'New Taiwan Dollar', countryCode: 'tw' },
  { code: 'KRW', name: 'South Korean Won', countryCode: 'kr' },
  { code: 'SGD', name: 'Singapore Dollar', countryCode: 'sg' },
  { code: 'INR', name: 'Indian Rupee', countryCode: 'in' },
  { code: 'THB', name: 'Thai Baht', countryCode: 'th' },
  { code: 'MYR', name: 'Malaysian Ringgit', countryCode: 'my' },
  { code: 'VND', name: 'Vietnamese Dong', countryCode: 'vn' },
  { code: 'PHP', name: 'Philippine Peso', countryCode: 'ph' },
  { code: 'IDR', name: 'Indonesian Rupiah', countryCode: 'id' },
  { code: 'SEK', name: 'Swedish Krona', countryCode: 'se' },
  { code: 'NZD', name: 'New Zealand Dollar', countryCode: 'nz' },
  { code: 'MXN', name: 'Mexican Peso', countryCode: 'mx' },
  { code: 'NOK', name: 'Norwegian Krone', countryCode: 'no' },
  { code: 'TRY', name: 'Turkish Lira', countryCode: 'tr' },
  { code: 'RUB', name: 'Russian Ruble', countryCode: 'ru' },
  { code: 'BRL', name: 'Brazilian Real', countryCode: 'br' },
  { code: 'ZAR', name: 'South African Rand', countryCode: 'za' },
  { code: 'AED', name: 'UAE Dirham', countryCode: 'ae' },
  { code: 'SAR', name: 'Saudi Riyal', countryCode: 'sa' },
  { code: 'PLN', name: 'Polish Złoty', countryCode: 'pl' },
];